### ISSUE TITLE
ガチャ本展開時アイテムが出ない

### ISSUE THREAD

**Issue by azutake** [chantake/MituyaProject#13]
ガチャ本を展開時アイテムが出てこない

**Comment by riou95** [comment]
原因…
・そもそも本に書いてあるコマンドが変更されてて現在は存在しない。
・ItemIDでgiveする本だからアイテムが付与されずに消える。

後者っぽい感じするけどどっちだろう。
本の情報見れればいいんだけどね。

**Comment by chantake** [comment]
新規作成でも出るので要調査 bukkitの仕様変更かもしれない
キャストに失敗しているのが問題

**Comment by chantake** [comment]
問題が解決できたためclose
