### ISSUE TITLE
コマンドショップsellでの価格の不具合

### ISSUE THREAD

**Issue by riou95** [chantake/MituyaProject#18]
現在sellコマンドは停止中です。

itemID 98：3（模様付き{入り}石レンガ{Cracked Stone Bricks}）によって錬金できてしまう不具合。
　レシピはハーフ石レンガ２つ。＝丸石４個で３個作れてしまう。

石の価格は8
４個で32

模様石レンガの売却価格は450
３個で1350

最低単位で1318mineの錬金が可能。

ＤＢにアクセスできる人お願いします。

**Comment by chantake** [comment]
本番環境確認後close

**Comment by fumitti** [comment]
fixed
