### ISSUE TITLE
バグ　スポンジブロックが壊れる

### ISSUE THREAD

**Issue by kamippa** [chantake/MituyaProject#31]
1.8から正式実装で破壊するとドロップできるはずなのですが　スポンジを破壊すると消えてしまいます

**Comment by riou95** [comment]
これ正式実装されたスポンジとID違うんじゃないか？

**Comment by chantake** [comment]
ドロップなどで手に入れれるので328的にはどのようにするのか検討する必要あり

**Comment by chantake** [comment]
検討後、修正するのであれば入手条件が変わると思うので別チケットを作成しなおしてください

このチケットは仕様ということでcloseします
