### ISSUE TITLE
/ms以下のすべてのコマンドが使用出来ない

### ISSUE THREAD

**Issue by azutake** [chantake/MituyaProject#52]
/ms info
/ms list
/ms price
/ms set
/ms protect
のコマンドが使用出来ずスポーンブロックの内容物の変更がエラーが出て出来ない(スポーンモンスターの変更が出来ない)

**Comment by fumitti** [comment]
稼働中lib更新により修復予定

**Comment by fumitti** [comment]
spigot更新によりfixed
