### ISSUE TITLE
コマンドショップでアイテムとして入手しないIDの物が買える

### ISSUE THREAD

**Issue by John-Yamada** [chantake/MituyaProject#62]
放送視聴者報告
17：4　旧アカシア原木（162）⇒　横向きオーク原木

17：4を買うとアカシアとして渡されるが置くとオークになる。
（報告者がどっちのつもりでどうやって17：4を買ったかは未詳）

など、テクスチャの無い旧アイテムや旧名で処理されるIDが残ってる

**Comment by fumitti** [comment]
17:4
17:5
売買停止処置
